[profile.default]
# Compiler settings
via_ir = true
optimizer = true
optimizer_runs = 200

# Project structure
src = "src"
out = "out"
libs = ["lib"]

# Remappings
remappings = [
      "forge-std/=lib/forge-std/src/",
      "solmate/=lib/solmate/",
      "vrf-contracts/=lib/vrf-contracts/",
      "BokkyPooBahsDateTimeLibrary/=lib/BokkyPooBahsDateTimeLibrary/contracts/"
]