[profile.default]
# Compiler settings
via_ir = true
code_size_limit = 1200000
optimizer = true
optimizer_runs = 200

# Project structure
src = "src"
out = "out"
libs = ["lib"]

# Remappings
remappings = [
    "forge-std/=lib/forge-std/src/",
    "ds-test/=lib/forge-std/lib/ds-test/src/",
    "solmate/=lib/solmate/",
    "vrf-contracts/=lib/vrf-contracts/"
]