[profile.default]
# Compiler settings
via_ir = true
optimizer = true
optimizer_runs = 200

# Project structure
src = "src"
out = "out"
libs = ["lib"]

# Remappings
remappings = [
      "forge-std/=lib/forge-std/src/",
      "BokkyPooBahsDateTimeLibrary/=lib/BokkyPooBahsDateTimeLibrary/contracts/",
      "solady/=lib/solady/src/",
      "@chainlink/contracts/=lib/chainlink-evm/contracts/",
      "@openzeppelin/contracts@4.9.6/=lib/openzeppelin-contracts/contracts/"
]