[lint]
lint_on_build = false

[profile.default]
# Compiler settings
via_ir = true
optimizer = true
optimizer_runs = 200

# Project structure
src = "src"
out = "out"
libs = ["lib"]

# Exclude non-deterministic simulation tests from default test runs
no_match_path = "test/simulation/*"

# Remappings
remappings = [
      "forge-std/=lib/forge-std/src/",
      "BokkyPooBahsDateTimeLibrary/=lib/BokkyPooBahsDateTimeLibrary/contracts/",
      "solady/=lib/solady/src/",
      "@chainlink/contracts/=lib/chainlink-evm/contracts/",
      "@openzeppelin/contracts@4.9.6/=lib/openzeppelin-contracts/contracts/"
]

[profile.simulation]
no_match_path = "NONE"
match_path = "test/simulation/*"

[invariant]
runs = 256
depth = 50

[profile.ci.invariant]
runs = 64
depth = 32