name: CI
on: [push, pull_request, workflow_dispatch]

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Foundry (nightly)
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - run: forge --version

      - name: Install deps
        run: |
          forge install --no-git \
            foundry-rs/forge-std@v1.9.7 \
            transmissions11/solmate@main \
            gelatodigital/vrf-contracts@main

      - name: Run Forge fmt
        run: forge fmt --check

      - name: Build contracts
        run: forge build

      - name: Run tests
        run: forge test -vvv
